import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                    '#003d9b',
        'primary-container':          '#0052cc',
        'primary-fixed':              '#dae2ff',
        'primary-fixed-dim':          '#b2c5ff',
        'on-primary':                 '#ffffff',
        'on-primary-fixed':           '#001848',
        'on-primary-fixed-variant':   '#0040a2',
        'on-primary-container':       '#c4d2ff',
        'secondary':                  '#006d39',
        'secondary-container':        '#91f8ae',
        'secondary-fixed':            '#91f8ae',
        'secondary-fixed-dim':        '#75db94',
        'on-secondary':               '#ffffff',
        'on-secondary-container':     '#00743c',
        'on-secondary-fixed':         '#00210d',
        'on-secondary-fixed-variant': '#005229',
        'tertiary':                   '#603b00',
        'tertiary-container':         '#805000',
        'tertiary-fixed':             '#ffddb8',
        'tertiary-fixed-dim':         '#ffb95f',
        'on-tertiary':                '#ffffff',
        'on-tertiary-container':      '#ffc988',
        'on-tertiary-fixed':          '#2a1700',
        'on-tertiary-fixed-variant':  '#653e00',
        'surface':                    '#f8f9fa',
        'surface-dim':                '#d9dadb',
        'surface-bright':             '#f8f9fa',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f3f4f5',
        'surface-container':          '#edeeef',
        'surface-container-high':     '#e7e8e9',
        'surface-container-highest':  '#e1e3e4',
        'surface-variant':            '#e1e3e4',
        'surface-tint':               '#0c56d0',
        'on-surface':                 '#191c1d',
        'on-surface-variant':         '#434654',
        'on-background':              '#191c1d',
        'background':                 '#f8f9fa',
        'outline':                    '#737685',
        'outline-variant':            '#c3c6d6',
        'inverse-surface':            '#2e3132',
        'inverse-on-surface':         '#f0f1f2',
        'inverse-primary':            '#b2c5ff',
        'error':                      '#ba1a1a',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'on-error-container':         '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:   '0.5rem',
        xl:   '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'container-padding-desktop': '40px',
        'container-padding-mobile':  '20px',
        'section-gap':               '32px',
        'gutter':                    '16px',
        'base':                      '8px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'ticket-display':     ['84px',  { lineHeight: '90px',  letterSpacing: '-0.04em', fontWeight: '700' }],
        'ticket-display-tv':  ['160px', { lineHeight: '1',     letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-lg':        ['32px',  { lineHeight: '40px',  letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px',  { lineHeight: '32px',  fontWeight: '600' }],
        'headline-md':        ['20px',  { lineHeight: '28px',  fontWeight: '500' }],
        'body-lg':            ['18px',  { lineHeight: '28px',  fontWeight: '400' }],
        'body-md':            ['16px',  { lineHeight: '24px',  fontWeight: '400' }],
        'label-caps':         ['12px',  { lineHeight: '16px',  letterSpacing: '0.05em', fontWeight: '600' }],
      },
      keyframes: {
        'pulse-scale': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%':       { opacity: '0.95', transform: 'scale(1.015)' },
        },
        'ticker': {
          '0%':   { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'progress-sweep': {
          '0%':   { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(300%)' },
        },
        'blink-in': {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.4' },
        },
        'slide-up': {
          '0%':   { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'pulse-scale':    'pulse-scale 2s ease-in-out infinite',
        'ticker':         'ticker 24s linear infinite',
        'progress-sweep': 'progress-sweep 2s linear infinite',
        'blink':          'blink-in 1.5s ease-in-out infinite',
        'slide-up':       'slide-up 0.3s ease-out',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
} satisfies Config;
