[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build",
  "npx tsup prisma/seed.ts --out-dir dist --format cjs --no-splitting"
]

[start]
cmd = "sh start.sh"
