FROM node:20-alpine AS builder
WORKDIR /app
RUN npm install -g pnpm
COPY apps/api/package.json ./
RUN pnpm install
COPY apps/api/ ./
RUN pnpm prisma generate
RUN pnpm build

FROM node:20-alpine AS runner
WORKDIR /app
RUN npm install -g pnpm
COPY --from=builder /app/package.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma
EXPOSE 3001
CMD ["node", "dist/server.js"]
